title: "Cormat Consulting"
description: "Materials Engineering & Consulting Services"
baseurl: ""
url: "https://cormatconsulting.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Appearance
minimal_mistakes_skin: "default" # Options: default, dark, contrast, mint, neon

# Author Information
author:
  name: "Cormat Consulting"
  email: "your@email.com"
  bio: "Specializing in Metallurgical Failure Analysis, Welding, Brazing, Corrosion Evaluation, and Process Optimization."
  avatar: "/assets/images/profile.jpg"

# Social Links
social:
  linkedin: "https://linkedin.com/in/yourprofile"
  github: "https://github.com/cormatconsulting"
  email: "your@email.com"

# Plugins (required for theme features)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

# Defaults (auto-apply layout to pages and posts)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true

# Optional SEO settings
google_site_verification: ""
lang: "en-US"
timezone: "America/Chicago"
